// Code generated by templ@v0.2.364 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "strconv"

func pages(pages []Page, website Website, count LinkCountResult, pageUrl string, prevPage string, nextPage string, addedPagesSet map[string]struct{}) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<html>")
		if err != nil {
			return err
		}
		err = header().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<body class=\"bg-gray-100\" id=\"container\">")
		if err != nil {
			return err
		}
		err = nav().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<div class=\"container mx-auto mt-12 p-4\"><a href=\"")
		if err != nil {
			return err
		}
		var var_2 templ.SafeURL = templ.URL(website.websiteURL())
		_, err = templBuffer.WriteString(templ.EscapeString(string(var_2)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" class=\"bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 focus:ring focus:ring-opacity-50 focus:ring-blue-300 focus:border-blue-300\">")
		if err != nil {
			return err
		}
		var_3 := `Refresh`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a><h1 class=\"text-4xl font-bold mb-6\">")
		if err != nil {
			return err
		}
		var_4 := `PAGES`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><form hx-delete=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(website.websiteURL()))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-swap=\"outerHTML\" hx-target=\"#container\" hx-indicator=\"#loadingText\"><button type=\"submit\" class=\"bg-red-500 text-white py-2 px-4 rounded hover:bg-red-600 focus:ring focus:ring-opacity-50 focus:ring-red-300 focus:border-red-300\">")
		if err != nil {
			return err
		}
		var_5 := `delete`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><div id=\"loadingText\" style=\"display:none\">")
		if err != nil {
			return err
		}
		var_6 := `Loading...`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></form><h1 class=\"text-xl mb-4\">")
		if err != nil {
			return err
		}
		var var_7 string = website.BaseUrl
		_, err = templBuffer.WriteString(templ.EscapeString(var_7))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><h2 class=\"text-2xl mb-4\">")
		if err != nil {
			return err
		}
		var_8 := `Added Pages:`
		_, err = templBuffer.WriteString(var_8)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h2><ul>")
		if err != nil {
			return err
		}
		for link := range addedPagesSet {
			_, err = templBuffer.WriteString("<li>")
			if err != nil {
				return err
			}
			var var_9 string = link
			_, err = templBuffer.WriteString(templ.EscapeString(var_9))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</li>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</ul><form hx-post=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(website.websitePagesURL()))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"#container\"><button type=\"submit\" class=\"bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 focus:ring focus:ring-opacity-50 focus:ring-blue-300 focus:border-blue-300\">")
		if err != nil {
			return err
		}
		var_10 := `Load more website content`
		_, err = templBuffer.WriteString(var_10)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><label for=\"processAll\">")
		if err != nil {
			return err
		}
		var_11 := `[ALL]`
		_, err = templBuffer.WriteString(var_11)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"checkbox\" name=\"processAll\" id=\"processAll\"><label for=\"processPageSize\">")
		if err != nil {
			return err
		}
		var_12 := `Page Size:`
		_, err = templBuffer.WriteString(var_12)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><select id=\"processPageSize\" name=\"processPageSize\"><option value=\"1\">")
		if err != nil {
			return err
		}
		var_13 := `1`
		_, err = templBuffer.WriteString(var_13)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option><option value=\"5\" selected=\"selected\">")
		if err != nil {
			return err
		}
		var_14 := `5`
		_, err = templBuffer.WriteString(var_14)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option><option value=\"10\">")
		if err != nil {
			return err
		}
		var_15 := `10`
		_, err = templBuffer.WriteString(var_15)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option><option value=\"25\">")
		if err != nil {
			return err
		}
		var_16 := `25`
		_, err = templBuffer.WriteString(var_16)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option><option value=\"50\">")
		if err != nil {
			return err
		}
		var_17 := `50`
		_, err = templBuffer.WriteString(var_17)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option><option value=\"100\">")
		if err != nil {
			return err
		}
		var_18 := `100`
		_, err = templBuffer.WriteString(var_18)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option></select></form>")
		if err != nil {
			return err
		}
		err = process(count, string(website.ID)).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<!--")
		if err != nil {
			return err
		}
		var_19 := ` Flexbox header - Can be omitted if not required `
		_, err = templBuffer.WriteString(var_19)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"flex mb-2 font-bold text-sm text-gray-600 border-b-2\"><div class=\"flex-1 p-2\">")
		if err != nil {
			return err
		}
		var_20 := `URL`
		_, err = templBuffer.WriteString(var_20)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"flex-1 p-2\">")
		if err != nil {
			return err
		}
		var_21 := `Keywords`
		_, err = templBuffer.WriteString(var_21)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"flex-1 p-2\">")
		if err != nil {
			return err
		}
		var_22 := `Title`
		_, err = templBuffer.WriteString(var_22)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"flex-2 p-2\">")
		if err != nil {
			return err
		}
		var_23 := `Content + Links`
		_, err = templBuffer.WriteString(var_23)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"flex-1 p-2\">")
		if err != nil {
			return err
		}
		var_24 := `Date Created`
		_, err = templBuffer.WriteString(var_24)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div><div class=\"flex-1 p-2\">")
		if err != nil {
			return err
		}
		var_25 := `Date Updated`
		_, err = templBuffer.WriteString(var_25)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></div>")
		if err != nil {
			return err
		}
		for _, item := range pages {
			_, err = templBuffer.WriteString("<div class=\"flex mb-2 border-b border-gray-200 hover:bg-gray-50\"><div class=\"flex-1 p-2\"><a target=\"_blank\" href=\"")
			if err != nil {
				return err
			}
			var var_26 templ.SafeURL = templ.SafeURL(item.URL)
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_26)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var var_27 string = item.URL
			_, err = templBuffer.WriteString(templ.EscapeString(var_27))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div><div>")
			if err != nil {
				return err
			}
			if item.ToProcess() {
				_, err = templBuffer.WriteString("<div>")
				if err != nil {
					return err
				}
				var_28 := `TO_PROCESS`
				_, err = templBuffer.WriteString(var_28)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
			} else {
				_, err = templBuffer.WriteString("<div>")
				if err != nil {
					return err
				}
				var_29 := `DONE`
				_, err = templBuffer.WriteString(var_29)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("<div>")
			if err != nil {
				return err
			}
			var var_30 string = item.PageStatus()
			_, err = templBuffer.WriteString(templ.EscapeString(var_30))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</div></div><div class=\"flex-1 p-2\">")
			if err != nil {
				return err
			}
			var var_31 string = item.Keywords
			_, err = templBuffer.WriteString(templ.EscapeString(var_31))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</div><div class=\"flex-1 p-2\">")
			if err != nil {
				return err
			}
			var var_32 string = item.Title
			_, err = templBuffer.WriteString(templ.EscapeString(var_32))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</div><div class=\"flex-2 p-2\"><details><summary class=\"cursor-pointer\">")
			if err != nil {
				return err
			}
			var_33 := `Content: (`
			_, err = templBuffer.WriteString(var_33)
			if err != nil {
				return err
			}
			var var_34 string = strconv.Itoa(len(item.Content))
			_, err = templBuffer.WriteString(templ.EscapeString(var_34))
			if err != nil {
				return err
			}
			var_35 := `) Links: (`
			_, err = templBuffer.WriteString(var_35)
			if err != nil {
				return err
			}
			var var_36 string = strconv.Itoa(len(item.Links))
			_, err = templBuffer.WriteString(templ.EscapeString(var_36))
			if err != nil {
				return err
			}
			var_37 := `)`
			_, err = templBuffer.WriteString(var_37)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</summary><h2>")
			if err != nil {
				return err
			}
			var_38 := `Content`
			_, err = templBuffer.WriteString(var_38)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2> ")
			if err != nil {
				return err
			}
			var var_39 string = item.Content
			_, err = templBuffer.WriteString(templ.EscapeString(var_39))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" <br><h2>")
			if err != nil {
				return err
			}
			var_40 := `Links`
			_, err = templBuffer.WriteString(var_40)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2><div><ul>")
			if err != nil {
				return err
			}
			for _, link := range item.Links {
				_, err = templBuffer.WriteString("<li>")
				if err != nil {
					return err
				}
				var var_41 string = link
				_, err = templBuffer.WriteString(templ.EscapeString(var_41))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</li>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</ul></div></details></div><div class=\"flex-1 p-2\">")
			if err != nil {
				return err
			}
			var var_42 string = item.DateCreated.Local().String()
			_, err = templBuffer.WriteString(templ.EscapeString(var_42))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</div><div class=\"flex-1 p-2\">")
			if err != nil {
				return err
			}
			var var_43 string = item.DateUpdated.Local().String()
			_, err = templBuffer.WriteString(templ.EscapeString(var_43))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</div></div>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</div></body></html>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
